profile {
  active = amd_ext_alone
}
amd_ext_alone {
  profile {
      name = "home_dev_with_macmini:mysql"
      desc = "[macbook + localhost::influxdb + macmini::mysql]"
  }
  influx {
    url = "http://localhost:38086"
    authToken = "sP0iAa9iJX504pU7Gxp3RGuxbF9ORCw9dE4mGJSpLaQoPuudnxZn7G3FxXBa6Q7FyEz3jVCfQwj9Y2p0Yh7xfQ=="
    org = "YG"
  }
  mysql {
    url = "jdbc:mysql://localhost:3306/horus?useSSL=false"
    user = "root"
    password = "root"
  }
  stocksql {
    url = "jdbc:mysql://horusa:3306/stock?useSSL=false"
    user = "root"
    password = "root"
  }
  komoran {
    dic = "/Users/ygkim/IdeaProjects/HorusDT/myDic.txt"
  }
  horus {
    crawl = "http://localhost:18070"
  }
}
home_dev {
  profile {
      name = "home_dev_with_macmini:mysql"
      desc = "[macbook + localhost::influxdb + macmini::mysql]"
  }
  influx {
    url = "http://horusa:38086"
    authToken = "sP0iAa9iJX504pU7Gxp3RGuxbF9ORCw9dE4mGJSpLaQoPuudnxZn7G3FxXBa6Q7FyEz3jVCfQwj9Y2p0Yh7xfQ=="
    org = "YG"
  }
  spark {
    master = "local[*]"
    jobs {
      word2vec {
        modelFile = "data/"
      }
      tdm {
        writeDB = "jdbc:mysql://horusa:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false"
      }
      lda {
        writeDB = "jdbc:mysql://horusa:3306/horus?useUnicode=true&characterEncoding=utf8&useSSL=false"
      }
    }
  }
  mysql {
    url = "jdbc:mysql://horusa:3306/horus?useSSL=false"
    user = "root"
    password = "root"
  }
  stocksql {
    url = "jdbc:mysql://horusa:3306/stock?useSSL=false"
    user = "root"
    password = "root"
  }
  komoran {
    dic = "/Users/ygkim/IdeaProjects/HorusDT/myDic.txt"
  }
  horus {
    crawl = "http://horusa:18070"
  }
}
home_live_studio {
  profile {
    name = "LIVE on M1 (STUDIO only)"
    desc = "LIVE"
  }
  influx {
    url = "http://influxdb208:8086"
    authToken = "sP0iAa9iJX504pU7Gxp3RGuxbF9ORCw9dE4mGJSpLaQoPuudnxZn7G3FxXBa6Q7FyEz3jVCfQwj9Y2p0Yh7xfQ=="
    org = "YG"
  }
  spark {
    master = "spark://spark-master:7077"
    jobs {
      word2vec {
        modelFile = "/opt/spark-data"
      }
      tdm {
        writeDB = "jdbc:mysql://mysql57:3306/horus?useSSL=false"
      }
      lda {
        writeDB = "jdbc:mysql://mysql57:3306/horus?useSSL=false"
      }
    }
  }
  mysql {
    url = "jdbc:mysql://mysql57:3306/horus?useSSL=false"
    user = "root"
    password = "root"
  }
  komoran {
    dic = "/opt/spark-apps/myDic.txt"
  }
  horus {
    crawl = "http://horus.crawld:8070"
  }
}