GET http://localhost:8086/api/v2/config
Authorization: Token CwgQWYIZKOcSpdlxwpfZfvDWQXpsfTlt7o2GD5hFAs4rTvHDF-7cfwmIQnmdocqL__5uoabCFGuf_GYzFQfxIA==

###

# curl -i http://httpbin.org/ipcurl --request POST
#  http://localhost:8086/api/v2/query?orgID=INFLUX_ORG_ID
#  --header 'Authorization: Token INFLUX_TOKEN'
#  --header 'Accept: application/csv'
#  --header 'Content-type: application/vnd.flux'
#  --data-binary 'from(bucket:"example-bucket")
#        |> range(start: -12h)
#        |> filter(fn: (r) => r._measurement == "example-measurement")
#        |> aggregateWindow(every: 1h, fn: mean)'
POST http://localhost:8086/api/v2/query?org=xwaves
Authorization: Token CwgQWYIZKOcSpdlxwpfZfvDWQXpsfTlt7o2GD5hFAs4rTvHDF-7cfwmIQnmdocqL__5uoabCFGuf_GYzFQfxIA==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket:"tfStudySample")
|> range(start: -6h)
|> filter(fn: (r) => r._measurement == "term_tf")
|> aggregateWindow(every: 6h, fn: sum)

###
# |> sort(columns: ["_value"], desc:true)
POST http://localhost:8086/api/v2/query?org=xwaves
Authorization: Token CwgQWYIZKOcSpdlxwpfZfvDWQXpsfTlt7o2GD5hFAs4rTvHDF-7cfwmIQnmdocqL__5uoabCFGuf_GYzFQfxIA==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket:"tfStudySample")
|> range(start: -10h)
|> filter(fn: (r) => r._measurement == "term_tf" and r.term == "국민")
|> window(every: 10m)
|> sum()
|> duplicate(column: "_stop", as: "_time")
|> window(every: inf)
|> sort(columns: ["_value"], desc:true)
|> limit(n: 3)

###

POST http://localhost:8086/api/v2/query?org=xwaves
Authorization: Token CwgQWYIZKOcSpdlxwpfZfvDWQXpsfTlt7o2GD5hFAs4rTvHDF-7cfwmIQnmdocqL__5uoabCFGuf_GYzFQfxIA==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket:"tfStudySample")
|> range(start: -8h)
|> filter(fn: (r) => r._measurement == "term_tf" and r._field == "tf")
|> sum()
|> filter(fn: (r) => r._value > 500)
|> sort(columns: ["_value"])
|> limit(n: 3)

###

POST http://localhost:8086/api/v2/query?org=xwaves
Authorization: Token CwgQWYIZKOcSpdlxwpfZfvDWQXpsfTlt7o2GD5hFAs4rTvHDF-7cfwmIQnmdocqL__5uoabCFGuf_GYzFQfxIA==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket: "tfStudySample")
  |> range(start: 1660115640)
  |> filter(fn: (r) => r["_measurement"] == "term_tf")
  |> filter(fn: (r) => r["_field"] == "tf")
  |> filter(fn: (r) => r["seedId"] == "9")
  |> filter(fn: (r) => r["term"] == "비" )
  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)
  |> yield(name: "sum")

###

POST http://macmini:8086/api/v2/query?org=YG
Authorization: Token lhb_6bgvAirOy1tb4fZ1FtWGR4VbTDDb0QEXCGJsRJcHJmO4RN1SYh4_ob-lnJUOLBKX4-SFFnVkv3H_up6UWQ==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket: "tfStudySample")
  |> range(start: -1h, stop: -1m)
  |> filter(fn: (r) => r["_measurement"] == "term_tf")
  |> filter(fn: (r) => r["_field"] == "tf")
  |> filter(fn: (r) => (r["term"] == "대통령" or r["term"] == "윤" or r["term"] == "말"))
  |> aggregateWindow(every: 5m, fn: sum, createEmpty: true)
  |> yield(name: "sum")

###

POST http://macmini:8086/api/v2/query?org=YG
Authorization: Token lhb_6bgvAirOy1tb4fZ1FtWGR4VbTDDb0QEXCGJsRJcHJmO4RN1SYh4_ob-lnJUOLBKX4-SFFnVkv3H_up6UWQ==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket: "tfStudySample")
  |> range(start: -1h, stop: -1m)
  |> filter(fn: (r) => r["_measurement"] == "term_tf")
  |> filter(fn: (r) => r["_field"] == "tf")
  |> filter(fn: (r) => (r["term"] == "대통령" or r["term"] == "윤" or r["term"] == "말"))
  |> aggregateWindow(every: 5m, fn: sum, createEmpty: true)
  |> pivot(rowKey: ["_time"], columnKey: ["term"], valueColumn: "_value")

###

POST http://macmini:8086/api/v2/query?org=YG
Authorization: Token lhb_6bgvAirOy1tb4fZ1FtWGR4VbTDDb0QEXCGJsRJcHJmO4RN1SYh4_ob-lnJUOLBKX4-SFFnVkv3H_up6UWQ==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket: "tfStudySample")
  |> range(start: -1h, stop: -1m)
  |> filter(fn: (r) => r["_measurement"] == "term_tf")
  |> filter(fn: (r) => r["_field"] == "tf")
  |> filter(fn: (r) => r["term"] == "대통령")
  |> aggregateWindow(every: 5m, fn: sum, createEmpty: true)
  |> yield(name: "sum")

###

POST http://macmini:8086/api/v2/query?org=YG
Authorization: Token lhb_6bgvAirOy1tb4fZ1FtWGR4VbTDDb0QEXCGJsRJcHJmO4RN1SYh4_ob-lnJUOLBKX4-SFFnVkv3H_up6UWQ==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket: "tfStudySample")
  |> range(start: -1h, stop: -1m)
  |> filter(fn: (r) => r["_measurement"] == "term_tf")
  |> filter(fn: (r) => r["_field"] == "tf")
  |> filter(fn: (r) => (r["term"] == "대통령" or r["term"] == "윤" or r["term"] == "말"))
  |> aggregateWindow(every: 5m, fn: sum, createEmpty: true)
  |> group(columns: ["_time"], mode:"by")
  |> sum(column: "_value")

###
POST http://macmini:8086/api/v2/query?org=YG
Authorization: Token lhb_6bgvAirOy1tb4fZ1FtWGR4VbTDDb0QEXCGJsRJcHJmO4RN1SYh4_ob-lnJUOLBKX4-SFFnVkv3H_up6UWQ==
Accept: application/csv
Content-Type: application/vnd.flux

from(bucket: "tfStudySample")
  |> range(start: -1h, stop: -1m)
  |> filter(fn: (r) => r["_measurement"] == "term_tf")
  |> filter(fn: (r) => r["_field"] == "tf")
  |> filter(fn: (r) => (r["term"] == "대통령" or r["term"] == "윤" or r["term"] == "말"))
  |> aggregateWindow(every: 5m, fn: sum, createEmpty: true)
  |> group(columns: ["_time"], mode:"by")
  |> sum(column: "_value")

### Create Remote
POST http://studio:38086/api/v2/remotes
Authorization: Token _VIqWr_c4Is6w7Lrpiw-Z_BC8vRg8e4nStlAWPYRVn1VrJkSV3LZWwX0cecY_IrgBiCkgngQwvXZRMpRRm_4wA==
Content-Type: application/json

{
  "allowInsecureTLS": false,
  "description": "Replication for AWS",
  "name": "HorusSync",
  "orgID": "b935e83f0c7dd94d",
  "remoteAPIToken": "r62gjCAsY2rWKrcGKxUf5eOFMUbZvuHSV497_ycxV6ceNOdcZJ3vXQsRHAEmDdF-QyK1dpylpic-GjZeCAD0mQ==",
  "remoteOrgID": "b466c4e3cc29963e",
  "remoteURL": "http://ec2-3-36-57-157.ap-northeast-2.compute.amazonaws.com:8086"
}

### Get Remote
GET http://studio:38086/api/v2/remotes?orgID=b935e83f0c7dd94d
Authorization: Token _VIqWr_c4Is6w7Lrpiw-Z_BC8vRg8e4nStlAWPYRVn1VrJkSV3LZWwX0cecY_IrgBiCkgngQwvXZRMpRRm_4wA==

### Create Replication Stream
POST http://studio:38086/api/v2/replications
Authorization: Token _VIqWr_c4Is6w7Lrpiw-Z_BC8vRg8e4nStlAWPYRVn1VrJkSV3LZWwX0cecY_IrgBiCkgngQwvXZRMpRRm_4wA==
Content-Type: application/json

{
  "dropNonRetryableData": false,
  "localBucketID": "e5af2fea14152e70",
  "maxAgeSeconds": 64800,
  "maxQueueSizeBytes": 33554470,
  "name": "Horus from local to AWS",
  "orgID": "b935e83f0c7dd94d",
  "remoteBucketName": "tfStudySample",
  "remoteID": "0ae00bb8ab678000"
}

### Get Replication
GET http://studio:38086/api/v2/replications?orgID=b935e83f0c7dd94d
Authorization: Token _VIqWr_c4Is6w7Lrpiw-Z_BC8vRg8e4nStlAWPYRVn1VrJkSV3LZWwX0cecY_IrgBiCkgngQwvXZRMpRRm_4wA==